"""Build metadata: meta.json payload and the human-readable pipeline report.

Both renderers consume the same BuildMeta so the committed JSON and
docs/pipeline-report.md can never disagree. The build timestamp is the only
non-deterministic field in either output.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from pipeline.config import FunnelCounts
from pipeline.gates import GateResult, render_gate_table
from pipeline.io import ArtifactInfo

_FUNNEL_LABELS: list[tuple[str, str]] = [
    ("raw", "raw transfer rows"),
    ("cleaned", "cleaned (dated, deduped, no self-moves)"),
    ("in_scope", "in scope (both clubs covered)"),
    ("with_v_before", "with v_before (<=180d, strict)"),
    ("observable", "observable for v_after (not censored)"),
    ("with_v_after", "with v_after in [180, 540]d"),
    ("non_loan", "minus suspected loans (the comps universe)"),
]

_CAVEATS = """\
## Caveats (stated, not papered over)

- **Loans**: detected structurally (zero-fee round-trips within 548 days) and excluded from
  the comps universe. Loans converted to permanent moves never round-trip and are
  structurally invisible.
- **Minutes coverage**: appearance data exists for the 14 legacy leagues from 2012 and for
  all 31 leagues only from 2024; games without any appearance rows are excluded from the
  possible-minutes denominator. `minutes_share_pre` and profile percentiles are nullable by
  design and never gate comp eligibility.
- **GK stats**: goals conceded use the full-game score of games the keeper appeared in, even
  for partial appearances; clean sheets require >=90 minutes played. League playoff rounds
  can settle on penalties; shootout goals are not part of these scores, but extra-time goals
  in such rounds are.
- **League tier**: per-season rank quartiles of leagues by median derived squad value
  (`(rank-1)*4 // n + 1`). Boundaries move with the market; this report prints the EUR
  ranges per tier for the latest season.
- **Squad values**: derived by summing members' latest valuation at season start (July 1),
  capped at 365 days of staleness; the upstream clubs table's market-value field is not used
  (unreliable).
- **Elo**: ratings come from public ClubElo mirrors (data: clubelo.com - thank you). ClubElo
  covers UEFA countries only, and the build enforces that: clubs in non-UEFA leagues are
  excluded from automatic name-matching (stage `excluded_non_uefa`) and rely on squad-value
  terciles (flagged, never silently dropped). club_seasons carries Elo as-of season start;
  transitions carry Elo as-of the transfer date. Percentiles are computed within a mirror
  snapshot.
- **Parquet bytes** can differ across machines/polars builds; the sha256 digests in meta.json
  make any rebuild drift visible.
"""


@dataclass(frozen=True)
class BuildMeta:
    repo: str
    revision: str
    built_at: str
    polars_version: str
    max_valuation_date: str
    censor_horizon: str
    funnel: FunnelCounts
    transitions_rows: int
    transitions_non_loan: int
    gates: list[GateResult]
    coverage: dict[str, float | int | str]
    constants: dict[str, object]
    artifacts: list[ArtifactInfo]
    warnings: list[str]
    tier_boundaries: list[str]


def meta_json(meta: BuildMeta) -> str:
    payload: dict[str, object] = {
        "source": {"source": "huggingface", "repo": meta.repo, "revision": meta.revision},
        "built_at": meta.built_at,
        "polars_version": meta.polars_version,
        "valuation_freshness": {
            "max_valuation_date": meta.max_valuation_date,
            "censor_horizon": meta.censor_horizon,
        },
        "funnel": {
            **{stage: getattr(meta.funnel, stage) for stage, _ in _FUNNEL_LABELS},
            "transitions_2012_plus": meta.transitions_rows,
            "transitions_non_loan_2012_plus": meta.transitions_non_loan,
        },
        "gates": [
            {
                "name": g.name,
                "passed": g.passed,
                "expected": g.expected,
                "actual": g.actual,
                "detail": g.detail,
            }
            for g in meta.gates
        ],
        "coverage": meta.coverage,
        "constants": meta.constants,
        "artifacts": {
            a.name: {"rows": a.rows, "bytes": a.n_bytes, "sha256": a.sha256} for a in meta.artifacts
        },
        "warnings": meta.warnings,
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def report_md(meta: BuildMeta) -> str:
    total_bytes = sum(a.n_bytes for a in meta.artifacts)
    lines: list[str] = [
        "# Pipeline report",
        "",
        "Generated by `uv run python -m pipeline.build`; the machine-readable twin is",
        "`server/data/processed/meta.json`. Every number is measured from the pinned build.",
        "",
        f"- Source: huggingface `{meta.repo}` @ `{meta.revision}`",
        f"- Valuation freshness (measured): **{meta.max_valuation_date}**"
        f" - censor horizon {meta.censor_horizon}",
        f"- Processed size: **{total_bytes / 1024 / 1024:.1f} MB** across"
        f" {len(meta.artifacts)} artifacts",
        "",
        "## Gates",
        "",
        render_gate_table(meta.gates),
        "",
        "## Funnel",
        "",
        "| stage | rows |",
        "|---|---|",
    ]
    lines += [f"| {label} | {getattr(meta.funnel, stage):,} |" for stage, label in _FUNNEL_LABELS]
    lines += [
        f"| transitions.parquet (season >= 2012, loans flagged) | {meta.transitions_rows:,} |",
        f"| ... of which non-loan | {meta.transitions_non_loan:,} |",
        "",
        "## Artifacts",
        "",
        "| artifact | rows | size | sha256 |",
        "|---|---|---|---|",
    ]
    lines += [
        f"| {a.name} | {a.rows:,} | {a.n_bytes / 1024:.0f} KB | `{a.sha256[:12]}...` |"
        for a in meta.artifacts
    ]
    lines += ["", "## Coverage", ""]
    lines += [f"- {key}: {value}" for key, value in sorted(meta.coverage.items())]
    if meta.tier_boundaries:
        lines += ["", "## League tier boundaries (latest season)", ""]
        lines += meta.tier_boundaries
    if meta.warnings:
        lines += ["", "## Warnings", ""]
        lines += [f"- {w}" for w in meta.warnings]
    lines += ["", _CAVEATS, f"_Built {meta.built_at}._", ""]
    return "\n".join(lines)
